services:
  web:
    build: php-apache
    container_name: app-name
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/app/

  db:
    image: mysql:5.7
    container_name: db-name
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./libdata:/var/libdata/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: mydb
      SERVICE_TAG: dev
      SERVICE_NAME: mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app-pdadmin
    links:
      - db
    restart: always
    ports:
      - 8081:80
